# Generated by Django 5.0.4 on 2024-07-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_alter_project_date_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_completed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
