# Generated by Django 5.0.4 on 2024-07-29 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0003_alter_project_date_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date_completed',
            new_name='date',
        ),
    ]
