# Generated by Django 5.0.4 on 2024-07-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0005_remove_certification_date_issued_certification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
