# Generated by Django 5.0.4 on 2024-07-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0006_certification_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='image_url',
        ),
        migrations.AddField(
            model_name='certification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certification_images/'),
        ),
    ]
